version : '3.8'

services:
  queue:
    image: rabbitmq:alpine
    ports:
      - '5672:5672'
      - '15672:15672'

  orders-db:
    build: orders_db/.
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
